name: moein_moradi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  xml2json: ^6.2.3
  url_strategy: ^0.3.0
  get_it: ^8.0.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFPro-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFPro-Black.ttf
          weight: 900
